windowrule {
  name = ankama-launcher
  float = on
  workspace = name:game1
  match:class = Ankama Launcher
  match:title = Ankama Launcher
}


windowrule {
  name = dofus
  float = on
  workspace = name:game1
  suppress_event = fullscreen
  match:class = Dofus.x64
}

windowrule {
  name = flameshot
  move = (0) (-750)
  pin = on
  float = on
  monitor = 0
  match:class = (flameshot)
  match:title = (flameshot)
}


windowrule {
  name = vesktop
  workspace = name:social1 silent
  match:class = vesktop
}

windowrule {
  name = spotify
  workspace = name:social2 silent
  match:class = Spotify
}
